language: node_js
node_js:
  - "4"
  - "6"
  - "7"
before_script:
  - npm install -g coveralls
script:
   - make
notifications:
  irc: "chat.freenode.net#brass-monkey"
after_success:
  - cat ./coverage/lcov.info | coveralls